### PR TITLE
Add SCAD Dashboard to terraform module

### LINKED ISSUE #928: Possibility of deploying SCAD dashboard as part of terraform code
Forgive my laziness at this stage, I would dive deep trying to understand how would one do it, but until I'm there I would very happy to hear feedback on how easy it would be implement in in terraform.

```console

# Updated console output below

☸ orbstack in management on  main [?] via 💠 management on ☁️  [redacted]-management took 1m17s 
❯ ./.venv/bin/cid-cmd deploy --dashboard-id scad-containers-cost-allocation
CLOUD INTELLIGENCE DASHBOARDS (CID) CLI 0.3.9 Beta

Loading plugins...
	Core loaded


Checking AWS environment...
	profile name: [redacted]-management
	accountId: [aws-account-id]
	AWS userId: [redacted]
	Region: us-east-1


                                          
Latest template: arn:aws:quicksight:us-east-1:223485597511:template/scad-containers-cost-allocation/version/2
Dashboard "scad-containers-cost-allocation" is not deployed

Required datasets: 
 - scad_cca_hourly_resource_view
 - scad_cca_summary_view


Looking by DataSetId defined in template...complete

There are still 2 datasets missing: scad_cca_hourly_resource_view, scad_cca_summary_view
Creating dataset: scad_cca_hourly_resource_view

? [athena-workgroup] Select Amazon Athena workgroup to use: primary

? [quicksight-datasource-id] Please choose DataSource (Select the first one if not sure): CID-CMD-Athena <CREATE NEW DATASOURCE>

? [quicksight-datasource-role] Please choose a QuickSight role. It must have access to Athena: aws-quicksight-service-role-v0
athena_datasource <cid.helpers.quicksight.datasource.Datasource object at 0x104f3bb90>                                                                                                                            

? [athena-database] Select AWS Athena database to use: athenacurcfn_default
Detected views: account_map
Missing views: scad_cca_hourly_resource_view
Checking if CUR is enabled and available...

? [cur-table-name] Please select CUR: default
	Athena table: default
	Resource IDs: yes
	SavingsPlans: yes
	Reserved Instances: yes


CRITICAL - Column 'split_line_item_net_split_cost' is not in (default). Cannot continue.
CRITICAL - Column 'split_line_item_net_unused_cost' is not in (default). Cannot continue.
CRITICAL - Column 'resource_tags_aws_eks_cluster_name' is not in (default). Cannot continue.
CRITICAL - Athena query failed: line 50:98: Column 't_scad_eks.split_line_item_net_split_cost' cannot be resolved
☸ orbstack in management on  main [?] via 💠 management on ☁️  [redacted]-management took 59s 
❯ ./.venv/bin/cid-cmd deploy --dashboard-id scad-containers-cost-allocation
CLOUD INTELLIGENCE DASHBOARDS (CID) CLI 0.3.9 Beta

Loading plugins...
	Core loaded


Checking AWS environment...
	profile name: [redacted]-management
	accountId: [aws-account-id]
	AWS userId: [redacted]
	Region: us-east-1


                                          
Latest template: arn:aws:quicksight:us-east-1:223485597511:template/scad-containers-cost-allocation/version/2
Dashboard "scad-containers-cost-allocation" is not deployed

Required datasets: 
 - scad_cca_hourly_resource_view
 - scad_cca_summary_view


Looking by DataSetId defined in template...complete

There are still 2 datasets missing: scad_cca_hourly_resource_view, scad_cca_summary_view
Creating dataset: scad_cca_hourly_resource_view

? [athena-workgroup] Select Amazon Athena workgroup to use: CID

? [quicksight-datasource-id] Please choose DataSource (Select the first one if not sure): CID-Athena CID-Athena (workgroup=CID)

? [athena-database] Select AWS Athena database to use: (Use arrow keys)                                                                                                                                           

Cancelled by user

☸ orbstack in management on  main [?] via 💠 management on ☁️  [redacted]-management took 2m55s 
❯ ./.venv/bin/cid-cmd deploy --dashboard-id scad-containers-cost-allocation
CLOUD INTELLIGENCE DASHBOARDS (CID) CLI 0.3.9 Beta

Loading plugins...
	Core loaded


Checking AWS environment...
	profile name: [redacted]-management
	accountId: [aws-account-id]
	AWS userId: [redacted]
	Region: us-east-1


                                                                                                                                                                                                                  
Latest template: arn:aws:quicksight:us-east-1:223485597511:template/scad-containers-cost-allocation/version/2
Dashboard "scad-containers-cost-allocation" is not deployed

Required datasets: 
 - scad_cca_summary_view
 - scad_cca_hourly_resource_view


Looking by DataSetId defined in template...complete

There are still 2 datasets missing: scad_cca_hourly_resource_view, scad_cca_summary_view
Creating dataset: scad_cca_hourly_resource_view

? [athena-workgroup] Select Amazon Athena workgroup to use: CID

? [quicksight-datasource-id] Please choose DataSource (Select the first one if not sure): CID-Athena CID-Athena (workgroup=CID)

? [athena-database] Select AWS Athena database to use: cid_cur
Detected views: account_map
Missing views: scad_cca_hourly_resource_view
Checking if CUR is enabled and available...

? [cur-table-name] Please select CUR: cur
	Athena table: cur
	Resource IDs: yes
	SavingsPlans: yes
	Reserved Instances: yes


^[[AColumn 'split_line_item_parent_resource_id' was added to CUR (cur).
Column 'split_line_item_reserved_usage' was added to CUR (cur).
Column 'split_line_item_actual_usage' was added to CUR (cur).
Column 'split_line_item_split_usage' was added to CUR (cur).
Column 'split_line_item_split_usage_ratio' was added to CUR (cur).
Column 'split_line_item_split_cost' was added to CUR (cur).
Column 'split_line_item_unused_cost' was added to CUR (cur).
Column 'split_line_item_net_split_cost' was added to CUR (cur).
Column 'split_line_item_net_unused_cost' was added to CUR (cur).
Column 'split_line_item_public_on_demand_split_cost' was added to CUR (cur).
Column 'split_line_item_public_on_demand_unused_cost' was added to CUR (cur).
Column 'resource_tags_aws_eks_cluster_name' was added to CUR (cur).
Column 'resource_tags_aws_eks_deployment' was added to CUR (cur).
Column 'resource_tags_aws_eks_namespace' was added to CUR (cur).
Column 'resource_tags_aws_eks_node' was added to CUR (cur).
Column 'resource_tags_aws_eks_workload_name' was added to CUR (cur).
Column 'resource_tags_aws_eks_workload_type' was added to CUR (cur).
CRITICAL - Athena query failed: line 77:16: Column 'product_instance_family' cannot be resolved
☸ orbstack in management on  main [?] via 💠 management on ☁️  [redacted]-management took 2m23s

# Updated console output above

☸ orbstack in management on  main [?] via 💠 management on ☁️  [redacted]-management took 2m23s 
❯ ./.venv/bin/cid-cmd deploy --dashboard-id scad-containers-cost-allocation
CLOUD INTELLIGENCE DASHBOARDS (CID) CLI 0.3.9 Beta

Loading plugins...
	Core loaded


Checking AWS environment...
	profile name: [redacted]-management
	accountId: [redacted]
	AWS userId: AWSReservedSSO_[redacted]/[redacted]@[redacted].com
	Region: us-east-1


                                                                                                                                                                                                                  
Latest template: arn:aws:quicksight:us-east-1:223485597511:template/scad-containers-cost-allocation/version/2
Dashboard "scad-containers-cost-allocation" is not deployed

Required datasets: 
 - scad_cca_hourly_resource_view
 - scad_cca_summary_view


Looking by DataSetId defined in template...complete

There are still 2 datasets missing: scad_cca_hourly_resource_view, scad_cca_summary_view
Creating dataset: scad_cca_hourly_resource_view

? [athena-workgroup] Select Amazon Athena workgroup to use: CID

? [quicksight-datasource-id] Please choose DataSource (Select the first one if not sure): CID-Athena CID-Athena (workgroup=CID)

? [athena-database] Select AWS Athena database to use: cid_cur
Detected views: account_map
Missing views: scad_cca_hourly_resource_view
Checking if CUR is enabled and available...

? [cur-table-name] Please select CUR: cur
	Athena table: cur
	Resource IDs: yes
	SavingsPlans: yes
	Reserved Instances: yes
```

From the console output it looks like beside dashboard itself, I would need to
make sure I have datasets all available.

### PR DESCRIPTION
**Pull request by ivan-kovnatskyi**
Possibly Closes #928.

- [ ] Handle datasets: scad_cca_hourly_resource_view, scad_cca_summary_view

### CODE REVIEW

**Comment by ivan-kovnatskyi** [comment]
When using cid-cmd tool it adds up these datasets:

```console
Required datasets: 
 - scad_cca_summary_view
 - scad_cca_hourly_resource_view

Using dataset scad_cca_hourly_resource_view: 4fa29375-72d2-4d7c-b4e6-1d73087ef431
Using dataset scad_cca_summary_view: e958dfc9-bfa7-44c3-af1e-ae5eb3ca0737
Dashboard scad-containers-cost-allocation exists. See https://us-east-1.quicksight.aws.amazon.com/sn/dashboards/scad-containers-cost-allocation
```

Meaning we need to handle that in code somehow.

**Comment by ivan-kovnatskyi** [comment]
It does not seem like reasonably to more forward since dashboard still not usable, until we configure datasets, which can't be done in scope of terraform module, at least at current stage.

**Comment by iakov-aws** [comment]
Hello Ivan, I am super happy to see you are working on this. We have a new concept that we are developing - CID plugins. We target every dasshboard to be installable with this plugin structure

**Comment by iakov-aws** [comment]
Great job! And i see a huge investment. Happy to followup on call if needed

**Comment by iakov-aws** [comment]
I would suggest getting to this after we implement plugins

https://github.com/aws-samples/aws-cudos-framework-deployment/pull/850

**Comment by ivan-kovnatskyi** [comment]
> Happy to followup on call if needed.

Thanks, that would be great. We're currently evaluating Split Cost Allocation as a concept, I think when we'll be ready we contact you, if that's okay, thanks!

**Pull request closed without merging**
