### PR TITLE
fix crawler permissions

### PR DESCRIPTION
**Pull request by iakov-aws**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by JoshiiSinfield** [comment]
+1 hitting this. Crawler is failing as not got permissions to log out.

**Comment by joseluis-fw** [comment]
Yes, crawler is broken, missing permissions.

**Comment by iakov-aws** [comment]
@yprikhodko @esc1144 @vmindru please can you approve this? looks like we need to publish this fix asap.

**Comment by iakov-aws** [comment]
@joseluis-fw @JoshiiSinfield was it CFN or TF install where you saw the issue?

**Comment by joseluis-fw** [comment]
@iakov-aws I am using the terraform setup for the dashboard, but it's only a wrapper for that cloudformation template.

**Review by yprikhodko — APPROVED** [review]

**Pull request merged**
